amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAVX3FIZ6QO4MEOLHP
  secretKey: 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
  bucketName: nethanbucketspringboot
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB